root: true

env:
  node: true

reportUnusedDisableDirectives: true

plugins:
  - comment-length
  - deprecation
  - "@eslint-community/eslint-comments"
  - import
  - promise
  - simple-import-sort
  - unicorn

extends:
  - eslint:recommended
  - plugin:comment-length/recommended
  - plugin:@eslint-community/eslint-comments/recommended
  - plugin:import/recommended
  - plugin:unicorn/recommended
  - plugin:prettier/recommended

rules:
  comment-length/limit-multi-line-comments: error
  comment-length/limit-single-line-comments: error
  deprecation/deprecation: error
  import/first: error
  import/no-default-export: error
  import/no-duplicates: error
  import/no-named-as-default-member: error
  import/no-named-as-default: error
  import/no-unresolved: off
  no-console: error
  promise/prefer-await-to-callbacks: error
  promise/prefer-await-to-then: error
  simple-import-sort/exports: error
  simple-import-sort/imports:
    - error
    - groups:
        - ["\\u0000$"] # Types
        - ["^\\u0000"] # Side-effects
        - ["^@?\\w"] # Packages
        - ["^"] # All other packages
        - ["^\\."] # Relative imports
  spaced-comment:
    - error
    - always
    - block:
        balanced: true
  unicorn/filename-case:
    - error
    - case: kebabCase
  unicorn/import-style: "off"
  unicorn/prevent-abbreviations:
    - error
    - replacements:
        desc:
          description: true
        sr:
          subreddit: true
  unicorn/switch-case-braces: [error, avoid]

overrides:
  - files: ["**/*.ts"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      projectService: true
    plugins:
      - "@typescript-eslint"
    extends:
      - plugin:@typescript-eslint/strict-type-checked
      - plugin:@typescript-eslint/stylistic-type-checked
      - plugin:import/typescript
    rules:
      "@typescript-eslint/array-type":
        - error
        - default: array-simple
      "@typescript-eslint/consistent-type-exports": error
      "@typescript-eslint/consistent-type-imports": error
      "@typescript-eslint/naming-convention":
        - error
        - selector: [class, interface, typeAlias, typeParameter]
          format: [PascalCase]
        - selector: default
          format: [camelCase]
          leadingUnderscore: allow
      "@typescript-eslint/no-inferrable-types": "off"
      "@typescript-eslint/no-non-null-assertion": "off"
      "@typescript-eslint/no-unused-vars":
        - error
        - args: all
          argsIgnorePattern: ^_
          caughtErrors: all
          caughtErrorsIgnorePattern: ^_
          destructuredArrayIgnorePattern: ^_
          varsIgnorePattern: ^_
          ignoreRestSiblings: true
      "@typescript-eslint/restrict-template-expressions":
        - error
        - allowAny: true
          allowBoolean: true
          allowNullish: true
          allowNumber: true
      "@typescript-eslint/require-await": "off"
      # This is already covered by @typescript-eslint/no-this-alias.
      unicorn/no-this-assignment: "off"

  - files: ["**/__tests__/**/*.ts"]
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
    rules:
      jest/expect-expect:
        - "error"
        - assertFunctionNames:
            - expect
            - n.done
